spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/training-hours
      auto-index-creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: training-hours-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true   # allow DTO serialization
  jms:
    listener:
      concurrency: 1

server:
  port: 8081

jwt:
  keys-path: secret

